nuxeo/nuxeo-core-binarymanager-cloud

- nuxeo-core-binarymanager-common/src/test/java/org/nuxeo/ecm/blob/AbstractTestCloudBinaryManager.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-3/8/
> fix-NXP-20195-unlimited-jce-7.10

- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3BinaryManager.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-6.0/9/
> fix-NXP-20756-blob-length-s3

- nuxeo-core-binarymanager-jclouds/src/main/java/org/nuxeo/ecm/blob/jclouds/JCloudsBinaryManager.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-dmetzler/33/
> fix-NXP-20605-20606-jclouds-bm-various-fix

- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3BinaryManager.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3BinaryManager.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-2/36/
> fix-NXP-20678-s3-gc

- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3BinaryManager.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3BinaryManager.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-7.10/14/
> fix-NXP-20678-s3-gc-7.10

- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3BinaryManager.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3BinaryManager.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-6.0/10/
> fix-NXP-20678-s3-gc-6.0

- nuxeo-core-binarymanager-common/src/test/java/org/nuxeo/ecm/blob/AbstractTestCloudBinaryManager.java
- nuxeo-core-binarymanager-s3/README.md
- nuxeo-core-binarymanager-s3/pom.xml
- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/CloudFrontBinaryManager.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/AbstractS3BinaryTest.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestCloudFrontRedirect.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3BinaryManager.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-akervern/17/
> feature-NXP-20219-download-using-cloudfront

- nuxeo-core-binarymanager-common/src/main/java/org/nuxeo/ecm/blob/AbstractCloudBinaryManager.java
- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3BinaryManager.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/169/
> feature-NXP-22217-extract-pure-blob-management

- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3BinaryManager.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-mcedica2/1/
> fix-NXP-23116-seting-bucket-endpoint

- nuxeo-core-binarymanager-s3/pom.xml
- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3BinaryManager.java
- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/status/S3BinaryManagerStatusProbe.java
- nuxeo-core-binarymanager-s3/src/main/resources/META-INF/MANIFEST.MF
- nuxeo-core-binarymanager-s3/src/main/resources/OSGI-INF/s3binarymanager-managment-contrib.xml
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3BinaryManagerStatus.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-mcedica2/5/
> feature-NXP-22927-integrate-probeAPI-into-status-servlet

- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3BinaryManager.java
https://jira.nuxeo.com/browse/NXP-23877
> NXP-23877: Don't provide both region and endpoint to S3 connector

- nuxeo-core-binarymanager-azure/pom.xml
- nuxeo-core-binarymanager-azure/src/main/java/org/nuxeo/ecm/blob/azure/AzureBinaryManager.java
- nuxeo-core-binarymanager-azure/src/test/java/org/nuxeo/ecm/blob/azure/TestAzureBinaryManager.java
- nuxeo-core-binarymanager-common/pom.xml
- nuxeo-core-binarymanager-common/src/main/java/org/nuxeo/ecm/blob/AbstractCloudBinaryManager.java
- nuxeo-core-binarymanager-jclouds/pom.xml
- nuxeo-core-binarymanager-jclouds/src/main/java/org/nuxeo/ecm/blob/jclouds/JCloudsBinaryManager.java
- nuxeo-core-binarymanager-s3/pom.xml
- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3BinaryManager.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc/356/
> cleanup-NXP-24090-replace-commons-lang-with-lang3

- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3BinaryManager.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/322/
> cleanup-NXP-24092-code-quality-5

- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3BinaryManager.java
This pull request adds the ability to the S3 binary manager to use a KMS-managed key for server-side encryption.  It adds a new crypt.kms.key property to configure the KMS key's identifier to be used.  When coupled with proper IAM roles, this makes for a very secure and easy to manage encryption setup.
> NXP-22949: Add the ability to use a server-side KMS managed key for S3 encryption

- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3BinaryManagerStatus.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-pierregautier/23/
> cleanup-NXP-24366-NXP-22544-cleanup-localdeploy

- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3BinaryManager.java
- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3DirectBatchHandler.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-lduarte/48/
> feature-NXP-24754-switch-to-sts-getfederationtoken

- nuxeo-core-binarymanager-jclouds/src/test/java/org/nuxeo/ecm/blob/jclouds/TestJCloudsBinaryManager.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-pierregautier/51/
> cleanup-NXP-22534-rework-fireframeworkstarted

- nuxeo-core-binarymanager-s3/pom.xml
- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3DirectBatchHandler.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/MockedS3DirectBatchHandler.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3DirectBatchHandler.java
- nuxeo-core-binarymanager-s3/src/test/resources/META-INF/MANIFEST.MF
- nuxeo-core-binarymanager-s3/src/test/resources/OSGI-INF/test-s3directupload-contrib.xml
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-pierregautier/80/
> NXP-25049-test-s3-direct-upload

- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3BinaryManager.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-gethin/157/
> fix-NXP-25319-s3-methods

- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3DirectBatchHandler.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-pierregautier2/31/
> fix-NXP-25533-fix-s3directupload-digest-usage

- nuxeo-core-binarymanager-common/src/test/java/org/nuxeo/ecm/blob/AbstractTestCloudBinaryManager.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/500/
> fix-NXP-25529-sonar-fixes-2

- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3BinaryManager.java
- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3DirectBatchHandler.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3DirectBatchHandler.java
- nuxeo-core-binarymanager-s3/src/test/resources/OSGI-INF/test-s3directupload-contrib.xml
https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-pierregautier3/11/
> NXP-25682: fix bucket prefix usage

- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3BinaryManager.java
- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3DirectBatchHandler.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3DirectBatchHandler.java
- nuxeo-core-binarymanager-s3/src/test/resources/OSGI-INF/test-s3directupload-contrib.xml
https://qa2.nuxeo.org/jenkins/view/All/job/TestAndPush/view/pierregautier/job/ondemand-testandpush-pierregautier-9.10/33/
> backport 9.10 NXP-25682: fix bucket prefix usage

- nuxeo-core-binarymanager-s3/pom.xml
- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3BinaryManager.java
- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3DirectBatchHandler.java
- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3Utils.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3DirectBatchHandler.java
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-9.10/49/
> feature-NXP-25075-aws-creds-provider-9.10

- nuxeo-core-binarymanager-azure/README.md
- nuxeo-core-binarymanager-azure/src/main/java/org/nuxeo/ecm/blob/azure/AzureBinaryManager.java
- nuxeo-core-binarymanager-azure/src/main/java/org/nuxeo/ecm/blob/azure/AzureFileStorage.java
- nuxeo-core-binarymanager-azure/src/main/java/org/nuxeo/ecm/blob/azure/AzureGarbageCollector.java
- nuxeo-core-binarymanager-azure/src/test/java/org/nuxeo/ecm/blob/azure/TestAzureBinaryManager.java
- nuxeo-core-binarymanager-common/src/main/java/org/nuxeo/ecm/blob/AbstractCloudBinaryManager.java
- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3BinaryManager.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3BinaryManager.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/625/
> fix-NXP-26581-transient-store-namespace

- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3BinaryManager.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3BinaryManager.java
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-8.10/104/
> fix-NXP-26697-upgrade-AWS-SDK-8.10

- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3BinaryManager.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-gethin/171/
> fix-NXP-26867-bucket-name

- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3BinaryManager.java
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-gethin-10.10/1/
> fix-NXP-26867-bucket-name-10-10

- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3DirectBatchHandler.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3BinaryManager.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3BinaryManagerWithSSE.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3BinaryManagerWithSSE2AndPolicy.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3DirectBatchHandler.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3DirectBatchHandlerWithSSE.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3DirectBatchHandlerWithSSEAndPolicy.java
- nuxeo-core-binarymanager-s3/src/test/resources/OSGI-INF/test-s3directupload-contrib.xml
PR created manually to early review, TP is coming
> Nxp 26976 s3 large file upload

- nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3DirectBatchHandler.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3BinaryManager.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3BinaryManagerWithSSE.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3BinaryManagerWithSSE2AndPolicy.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3DirectBatchHandler.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3DirectBatchHandlerWithSSE.java
- nuxeo-core-binarymanager-s3/src/test/java/org/nuxeo/ecm/core/storage/sql/TestS3DirectBatchHandlerWithSSEAndPolicy.java
- nuxeo-core-binarymanager-s3/src/test/resources/OSGI-INF/test-s3directupload-contrib.xml
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-pierregautier2/84/
> NXP-26976-s3-large-file-upload-10.10
